apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-search
spec:
  selector:
    matchLabels:
      app: distributed-search
  replicas: 3
  template:
    metadata:
      labels:
        app: distributed-search
    spec:
      containers:
        - name: distributed-search
          image: leonardorocha1990/distributed-search:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k3s
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10