apiVersion: v1
kind: Service
metadata:
  name: distributed-search
  labels:
    app: distributed-search
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30712
      protocol: TCP
      name: distributed-search
  selector:
    app: distributed-search